[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "undervaluation-screener"
version = "1.0.0"
description = "Professional undervalued stock screening algorithm with composite scoring"
requires-python = ">=3.9"
authors = [{name = "BMad Team"}]
readme = "README.md"
dependencies = [
    "pandas>=2.0",
    "numpy>=1.24",
    "yfinance>=0.2.43",
    "click>=8.1",
    "PyYAML>=6.0",
    "tabulate>=0.9",
    "tqdm>=4.66",
    "pydantic>=2.7",
    "scipy>=1.10.0",
    "statsmodels>=0.14.0",
    "requests>=2.28.0",
    "python-dateutil>=2.8.0",
    "matplotlib>=3.6.0",
    "seaborn>=0.12.0",
    "plotly>=5.15.0",
    "openpyxl>=3.1.0",
    "xlsxwriter>=3.1.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0"
]

[project.scripts]
uv-screen = "undervaluation.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
